version: 2.1

orbs:
  go: circleci/go@1.9.0

jobs:
  test:
    docker:
      - image: cimg/go:1.25.0
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Run tests
          command: go test -v ./...
      - run:
          name: Run tests with coverage
          command: go test -coverprofile=coverage.out ./...
      - run:
          name: Display coverage
          command: go tool cover -func=coverage.out

  build:
    docker:
      - image: cimg/go:1.25.0
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Build application
          command: |
            mkdir -p bin
            go build -o bin/app .
      - run:
          name: Verify build
          command: ls -lh bin/
      - persist_to_workspace:
          root: .
          paths:
            - bin

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Trigger Render Deployment
          command: |
            curl -X POST \
              "${RENDER_DEPLOY_HOOK_URL}" \
              -H "Content-Type: application/json"

workflows:
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
